author: SpleefLeague
authors: [Joba, Akaiyo, Manuman]
description: SpleefLeague Core Plugin
main: com.spleefleague.core.SpleefLeague
name: SpleefLeagueCore
url: http://www.spleefleague.com/
version: 1.4
api-version: 1.13
softdepend: [ProtocolLib]
loadbefore: [Commands, Parkour, SuperSpleef]