author: SpleefLeague
authors: [Joba, Akaiyo, Manuman]
description: SpleefLeague Core Plugin
main: com.spleefleague.core.SpleefLeague
name: SpleefLeagueCore
url: http://www.spleefleague.net/
version: 0.1
commands:
    setrank:
        description: Command to set ranks
        aliases: []
        usage: |
            /<command> <player> <rank>
    reply:
        description: Reply to the last private message
        aliases: [r]
        usage: |
            /<command> <message>
    tell:
        description: A command to send a private message to a certain command
        aliases: [w, msg]
        usage: |
            /<command> <player> <message>
    debug: 
        description: Load a debug class at runtime
        aliases: [d,rd]
        usage: |
            /<command> <hastebinId>
            /<command> cmd <debuggerId> <cmd> [args]
            /<command> stop <debuggerId>
    ping:
        description: Shows your own ping, or possibly that of another if you're helper+
        aliases: []
        usage:
            /<command> [username]
    gamemode:
        description: Sets a player's gamemode
        aliases: [gm]
        usage: |
            /<command> <gamemode> [player]
    warn:
        description: warn a player
        aliases: []
        usage: |
            /<command> <player> <message>
    kick:
        description: kick a player
        aliases: []
        usage: |
            /<command> <player> <message>
    tempban:
        description: tempban a player
        aliases: []
        usage: |
            /<command> <player> <duration> <message>
    ban:
        description: ban a player
        aliases: []
        usage: |
            /<command> <player> <message>
    unban:
        description: unban a player
        aliases: []
        usage: |
            /<command> <player> <message>
    surrender:
        description: surrenders the current game
        aliases: [ragequit]
        usage: |
            /<command>
    leave:
        description: Leaves the current queue
        aliases: [l]
        usage: |
            /<command>
    cancel:
        description: Cancels a game
        aliases: []
        usage: |
            /<command> <player>
    cancelall:
        description: Cancels every game
        aliases: []
        usage: |
            /<command>
    infractions:
        description: Displays the infractions of a player
        aliases: [inf]
        usage: |
            /<command> <player> [page]
    spectate:
        description: Spectates a battle
        aliases: []
        usage: |
            /<command> [player]
    spawn:
        description: Teleports a player back to spawn
        aliases: []
        usage: |
            /<command>
    back:
        description: Teleports a player back to their last location
        aliases: []
        usage: |
            /<command>
    tp:
        description: Teleports you to another player
        aliases: []
        usage: |
            /<command> <target>
    tppos:
        description: Teleports a player to certain coordinates
        aliases: []
        usage: |
            /<command> [target] <x> <y> <z>
    tphere:
        description: Teleports a player to you
        aliases: []
        usage: |
            /<command> <target>
    invsee:
        description: Open a player's inventory
        aliases: []
        usage: |
            /<command> <target>
    points:
        description: Displays a player's Spleef/Jump stats
        aliases: [stats, rating]
        usage: |
            /<command>
    endgame:
        description: Requests the current battle to be cancelled
        usage:
            /<command>
    staffchat:
        description: Staff intern chat
        aliases: [sc]
        usage:
            /<command> <message>
    pauseall:
        description: Pauses all queues
        usage:
            /<command>
    unpauseall:
        description: Unpauses all queues
        usage:
            /<command>
    reloaddata:
        description: Reloads something
        usage:
            /<command> <ranks/settings>
    warp: 
        description: Warp command
        usage: |
            /<command> 
            /<command> <warpName>
    setwarp: 
        description: Set a new Warp
        usage:
            /<command> <warpName>
    deletewarp: 
        description: Delete a Warp
        usage:
            /<command> <warpName>
    playerinfo: 
        description: Shows the playerdata if a player
        aliases: [pi, pd]
        usage:
            /<command> [player]
    map: 
        description: Gives the player an animated map
        usage:
            /<command> <create|destroy> <URL|ID>
    register: 
        description: Create a new forum account
        usage:
            /<command> <email>
    spawns:
        description: List all SL spawns
        usage:
            /<command>
    fspeed:
        description: Change flyspeed
        usage:
            /<command> <speed>
    setmax:
        description: Sets the current server slot size
        usage:
            /<command> <size>
    ticket:
        description: Opens a new ticket
        usage:
            /<command> <message>
    ticketreply:
        description: Replies to a ticket
        aliases: [treply]
        usage:
            /<command> <player> <message>
    challenge:
        description: Accept/Decline a challenge
        usage:
            /<command> <accept|decline> <player>
    fly:
        description: Toggles flymode
        usage:
            /<command>
    join:
        description: Joins a server
        aliases: [server]
        usage:
            /<command> <server>
    rules:
        description: Shows you the server rules
        usage:
            /<command> [page]
    dcmd:
        description: Manages dynamic commands
        usage: |
            /<command> add <haste> - register/update new command from haste id
            /<command> remove <name> - disables a command
            /<command> list [page] - lists enabled commands
            /<command> disabled [page] - lists disabled commands
            /<command> enable <name> - re-enables a disabled command
    stafflist:
        description: List online staff
        aliases: [sl]
        usage: |
            /<command>
    skull:
        description: Give the executor a skull
        aliases: []
        usage: |
            /<command> <head-name>
    colorarmor:
        description: Color the leather armor in your hand
        aliases: []
        usage: |
            /<command> <red> <green> <blue> - Colors from 0-255
    sping:
        description: lists everyone or some people's pings
        aliases: []
        usage: |
            /<command> [usernames...]
    balancing:
        description: Server balancing management command.
        usage: |
            /<command> <refresh>
    globalschematic:
        description: Builder schematic management command.
        aliases: [gs]
        usage: |
            /<command> <save|load|list> [name]
    broadcast:
        description: Broadcast something server-wide (or locally if need be).
        aliases: [bc]
        usage: |
            /<command> [local] <message>
    settemprank:
        description: Command to set temporary ranks
        aliases: []
        usage: |
            /<command> <player> <rank> <time in hours>
    grantcurrency:
        description: Command to change amount of coins/premium credits player has
        aliases: []
        usage: |
            /<command> <player> <currency type> <amount>
